$(document).ready(function(){
    $("#btn1").click(function(){
        $("#kwadrat").fadeIn()
        $("#trojkat").fadeIn("slow")
        $("#okrag").fadeIn(800)
    })
    $("#btn2").click(function(){
        $("#kwadrat").fadeOut()
        $("#trojkat").fadeOut("slow")
        $("#okrag").fadeOut(800)
    })
    $("#btn3").click(function(){
        $("#kwadrat").fadeToggle()
        $("#trojkat").fadeToggle("slow")
        $("#okrag").fadeToggle(800)
    })
    $("#btn4").click(function(){
        $("#kwadrat").fadeTo(0,0.4)
        $("#trojkat").fadeTo("slow",0.4)
        $("#okrag").fadeTo(800,0.4)
    })
    $("#btn5").click(function(){
        $("p").slideUp()
    })
    $("#btn6").click(function(){
        $("p").slideDown()
    })
    $("#btn7").click(function(){
        $("p").slideToggle()
    })
    $("#btn8").click(function(){
        $("#drugikwadrat").animate({height:'1000px',width:'10px'},"slow",function(){
            $("#drugikwadrat").css("background-color",'green')
            $("#drugikwadrat").css("color",'cyan')
            $("#drugikwadrat").css("font-size",'100px')
        })
        $("#drugikwadrat").animate({height:'10px',width:'1000px'},"slow",function(){
            $("#drugikwadrat").css("background-color",'red')
            $("#drugikwadrat").css("color",'magenta')
            $("#drugikwadrat").css("font-size",'10px')
        })
        $("#drugikwadrat").animate({height:'1000px',width:'10px'},"slow",function(){
            $("#drugikwadrat").css("background-color",'green')
            $("#drugikwadrat").css("color",'cyan')
            $("#drugikwadrat").css("font-size",'100px')
        })
        $("#drugikwadrat").animate({height:'10px',width:'1000px'},"slow",function(){
            $("#drugikwadrat").css("background-color",'red')
            $("#drugikwadrat").css("color",'magenta')
            $("#drugikwadrat").css("font-size",'10px')
        })
        $("#drugikwadrat").animate({height:'1000px',width:'10px'},"slow",function(){
            $("#drugikwadrat").css("background-color",'green')
            $("#drugikwadrat").css("color",'cyan')
            $("#drugikwadrat").css("font-size",'100px')
        })
        $("#drugikwadrat").animate({height:'10px',width:'1000px'},"slow",function(){
            $("#drugikwadrat").css("background-color",'red')
            $("#drugikwadrat").css("color",'magenta')
            $("#drugikwadrat").css("font-size",'10px')
        })
    })
    $("#btn9").click(function(){
        $("#drugikwadrat").stop()
    })
    $("#btn10").click(function(){
        $("#drugikwadrat").css("color",'blue').slideUp(1500).slideDown(1000)
    })
    $("#btn11").click(function(){
        $("#drugikwadrat").animate({height:'1000px',width:'10px'},"slow",function(){
            $("#drugikwadrat").css("height",'200px')
            $("#drugikwadrat").css("width",'200px')
            $("#drugikwadrat").css("color",'magenta')
        })
    })
    $("#btn12").click(function(){
        $("#drugikwadrat").css("color",'blue').slideUp(100).slideDown(100).slideUp(100).slideDown(100).slideUp(100).slideDown(100)
    })
})