$(document).ready(function(){
    $("#btn1").click(function(){
        $("#kwadrat").fadeIn()
        $("#trojkat").fadeIn("slow")
        $("#okrag").fadeIn(800)
    })
    $("#btn2").click(function(){
        $("#kwadrat").fadeOut()
        $("#trojkat").fadeOut("slow")
        $("#okrag").fadeOut(800)
    })
    $("#btn3").click(function(){
        $("#kwadrat").fadeToggle()
        $("#trojkat").fadeToggle("slow")
        $("#okrag").fadeToggle(800)
    })
    $("#btn4").click(function(){
        $("#kwadrat").fadeTo(0,0.4)
        $("#trojkat").fadeTo("slow",0.4)
        $("#okrag").fadeTo(800,0.4)
    })
    $("#btn5").click(function(){
        $("p").slideUp()
    })
    $("#btn6").click(function(){
        $("p").slideDown()
    })
    $("#btn7").click(function(){
        $("p").slideToggle()
    })
    $("#btn8").click(function(){
        $("#drugikwadrat").animate({height:'1000px',width:'10px',backgroundColor:'yellow'},"slow")
        $("#drugikwadrat").animate({height:'10px',width:'1000px',color:'black'},"slow")
        $("#drugikwadrat").animate({height:'1000px',width:'10px',color:'cyan'},"slow")
        $("#drugikwadrat").animate({height:'10px',width:'1000px',color:'magenta'},"slow")
        $("#drugikwadrat").animate({height:'1000px',width:'10px',color:'blue'},"slow")
        $("#drugikwadrat").animate({height:'10px',width:'1000px',color:'orange'},"slow")
    })
})